### ISSUE TITLE
Options: permit to select shell...

### ISSUE THREAD

**Issue by nicola-lunghi** [dzsessona/QuickOpener-NetBeans#80]
Hi
I use ubuntu mate and my shell is mate-terminal and my file manager is called caja
Can you add an option on the plugin options to select the command to run for the shell and for the terminal???

Thanks
Nick

**Comment by Druvid** [comment]
I'd also like to have this option. In my case though, it was easy to fix from the source code:
In [OperatingSystem.java](https://github.com/dzsessona/QuickOpener-NetBeans/blob/master/QuickOpener/src/main/java/com/sessonad/oscommands/detector/OperatingSystem.java) on line 19 (since I use xcfe) I just replaced `"thunar ", "thunar "` with `"spacefm ", "spacefm "` and then built it with maven. In your case, you would have to change a bit more of the code (including in other classes) since there is no LINUX_MATE type in OperatingSystem.java. Maybe the developers will add support for more distros/desktop environments if they get more requests for this. :)

**Comment by markiewb** [comment]
Or you provide a pull-request which moves the hard-coded string into an
option?!

Den 6 juli 2017 5:14 em skrev "Druvid" <notifications@github.com>:

I'd also like to have this option. In my case though, it was easy to fix
from the source code:
In OperatingSystem.java
<https://github.com/dzsessona/QuickOpener-NetBeans/blob/master/QuickOpener/src/main/java/com/sessonad/oscommands/detector/OperatingSystem.java>
on line 19 (since I use xcfe) I just replaced "thunar ", "thunar "
with "spacefm
", "spacefm " and then built it with maven. In your case, you would have to
change a bit more of the code (including in other classes) since there is
no LINUX_MATE type in OperatingSystem.java. Maybe the developers will add
support for more distros/desktop environments if they get more requests for
this. :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dzsessona/QuickOpener-NetBeans/issues/80#issuecomment-313426621>,
or mute the thread

**Comment by markiewb** [comment]
Fixed via PR by @javatlacati. 

Please try the SNAPSHOT and give feedback 
https://github.com/dzsessona/QuickOpener-NetBeans/releases/tag/1.2.0-SN
